language: scala
scala:
- 2.11.1
jdk:
- oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION package
deploy:
  provider: releases
  api_key:
    secure: klyHgjzeWE96Dj89Y3Ft+tHkBfIaSXTTtDP/qRtMSwcQsBPwBjdXvjac/1+9mSmqJ+vDBd0DjMULbNzNgGyogSd8gGDqKBpjraxSKYRDFcBVItRGenOmQzIpvuryRkhGPBGLlqUpaRbd98ZNVQ2OJlhwwdWlfRo55z+jVhfxlX8=
  file: target/scala-2.11/gitbucket-helloworld-plugin_2.11-1.0.jar
  on:
    repo: kaakaa/gitbucket-helloworld-plugin
    tags: true
  skip_cleanup: true
